In [36]:
arr=[1,2,3,4,5,6,7,8,9]
len(arr)**0.5

3.0

In [12]:
arr=[1,2,3,4,5,6,7,8,9]
a=[]
b=[]
s=0
for i in range(int(len(arr)**0.5)):
    
    for j in range(int(len(arr)**0.5)):
        b.append(arr[s])
        s=s+1
    a.append(b) 
    b=[]  
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
print(range(1,2,6))

range(1, 2, 6)


In [15]:
import numpy as np
print(np.arange(6))

[0 1 2 3 4 5]


In [18]:
arr=np.arange(0,18,2).reshape(3,3)
arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [20]:
arr2=np.arange(0,9,1).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr+arr2

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [23]:
arr*arr2

array([[  0,   2,   8],
       [ 18,  32,  50],
       [ 72,  98, 128]])